apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  name: boinc.berkeley.edu
  labels:
    ui.platform-mesh.io/content-for: boinc.berkeley.edu
spec:
  latestResourceSchemas:
    - v1alpha1.boincworkloads.boinc.berkeley.edu
    - v1alpha1.boincprojects.boinc.berkeley.edu
  permissionClaims:
    - all: true
      group: ""
      resource: events
    - all: true
      group: ""
      resource: secrets
    - all: true
      group: ""
      resource: namespaces
