apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  name: boinc.platform-mesh.io
spec:
  latestResourceSchemas:
    - v1alpha1.boincworkloads.boinc.platform-mesh.io
    - v1alpha1.boincprojects.boinc.platform-mesh.io
  permissionClaims:
    - all: true
      group: ""
      resource: events
    - all: true
      group: ""
      resource: secrets
